# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute minimum cost perfect matching
#'
#' @param nvertices The number of vertices in the graph.
#' @param nedges The number of edges in the graph.
#' @param edges A dataframe representing the edges and their cost with columns `from`, `to` and
#' `edges`.
#'
#' @return A list with entries `cost` (a number) and `edges` (a matrix).
#'
#' @export
#'
minimum_cost_perfect_matching <- function(nvertices, nedges, edges) {
    .Call(`_mcpm_minimum_cost_perfect_matching`, nvertices, nedges, edges)
}

